version: '2'
services:
  api:
    build: flashair-sync-monitor-api
    volumes:
      - ./files:/files
    ports:
      - "8080:8080"

  flashairwatch:
    build: flashair-sync-monitor-watcher
    environment:
      - FLASH_AIR_IP=192.168.0.123
    volumes:
      - ./files:/files