version: '2'
services:
  api:
    build: flashair-sync-monitor-api
    volumes:
      - "${files}:/files"
    ports:
      - "${PORT}:8080"

  frontend:
    build: flashair-sync-monitor-ionic
    ports:
      - "${PORT}:8080"

  flashairwatch:
    build: flashair-sync-monitor-watcher
    environment:
      - "FLASH_AIR_IP=${FLASH_AIR_IP}"
    volumes:
      - "${files}:/files"
